In [2]:
import numpy as np
import math

In [5]:
### Initial Conditions
#coords = np.array([[0.75,0.25,0.25],
#                   [1.0,0.0,0.0],
#                   [1.0,1.0,0.0],
#                   [0.0,1.0,0.0],
#                   [0.0,0.0,1.0],
#                   [1.0,0.0,1.0],
#                   [1.0,1.0,1.0],
#                   [0.0,1.0,1.0]])
coords = np.array([0.891988194760370612, -0.118356774288699299, -0.023872397851855739])
rk = 0.363549250661963474 #maxPM also
timeDes = 0.000000358569035659
v2 = 31.2867
alpha = 1.00
tvisc = 0.0000000028226385
visc = 0.00003756
tdr = 0.09*0.052252516556007766*3.098736925423469022e+07
tke = 0.052252516556007766
#dudx = np.array([[-0.213822, -0.0691108, -0.546687],           # du/dx, dv/dx, dw/dx
#         [3.39258, -0.143084, -0.286583],              # du/dy, dv/dy, dw/dy
#         [-0.283958, -0.00582199, 0.358635]])          # du/dz, dv/dz, dw/dz
#avgDudx = np.array([[0.00474285, 0.00812532, -0.00487031],     # du/dx, dv/dx, dw/dx
#         [1.21798, 0.138779, 0.301419],                # du/dy, dv/dy, dw/dy
#         [0.372395, 0.00632533, -0.124443]])           # du/dz, dv/dz, dw/dz
#nuSF = np.array([[0.0388851, 0.402091E-10, -0.601585E-12],   
#         [0.402091E-10, 0.00299385, -0.178607E-12],    
#         [-0.601585E-12, -0.178607E-12, 0.0421588]])   

#dudx = "-0.406557E+00  0.275124E+00  0.312125E+00  0.344887E+01 -0.229688E+00 -0.118359E+01  0.184561E+00  0.231011E+00  0.658679E+00"
#dudx = dudx.split()
#dudx = map(float, dudx)
#dudx = np.asarray(dudx)
#dudx = dudx.reshape(3,3)

#avgDudx = "-0.234391E-01 -0.308303E-02  0.124282E-01  0.333309E+01  0.823876E-01  0.437521E+00 -0.460390E-01 -0.447557E-01 -0.955394E-01"
#avgDudx = avgDudx.split()
#avgDudx = map(float, avgDudx)
#avgDudx = np.asarray(avgDudx)
#avgDudx = avgDudx.reshape(3,3)

avgDudx = np.array([[5815.135862199717848853,15258.202229787613759981,0.015762345965326219],[-2216.32333984757633516,-5815.239285149380521034,-0.005480395056548737],[5.690050943440175146,14.938017730791141702,-0.01182902716973124]])
dudx = avgDudx

#nuSF = "0.452799E-01  0.966846E-11  0.192674E-11  0.966846E-11  0.327168E-02 -0.324346E-09  0.192674E-11 -0.324346E-09  0.490920E-01"
#nuSF = nuSF.split()
#nuSF = map(float, nuSF)
#nuSF = np.asarray(nuSF)
#nuSF = nuSF.reshape(3,3)

#0.369599 0.00387168 0.392699

metric = np.array([[0.005243657027190821,-0.001994924796099943,0.0],[-0.001994924796099943,0.000772004663223833,0.0],[0.0,0.0,0.005569860945288242]])
dt = 0.001

#parse = "  0.314159E+01  0.116494E+01  0.589049E+00  0.693200E+00  0.693200E+00  0.110287E+01  0.384089E+00  0.782802E+00  0.931920E-01  0.851367E+00  0.938947E+00 -0.672486E+00 -0.989472E-01  0.453700E-01 -0.203258E+01  0.720756E+00  0.113587E+01 -0.548485E+00 -0.176389E+00 -0.224684E-01  0.185653E-02  0.116241E-01  0.437705E-02 -0.143330E+01  0.133019E+00 -0.250111E+00  0.261884E+00 -0.457160E-01 -0.106902E+00  0.392466E-01  0.405826E-10  0.607174E-12  0.405826E-10  0.302169E-02 -0.180186E-12  0.607174E-12 -0.180186E-12  0.425507E-01"
#parse = "1.1088 1.19195 2.74889 0.112311 0.112311 1.16305 0.673139 0.981859 0.172237 1.4149 1.6456 0.0467721 -0.208942 0.0439817 0.03631 0.15586 0.224608 -0.223903 0.0856052 -0.2139 -0.00034071 -1.21604 -0.0078869 -0.00277373 0.00547406 0.00223157 -0.00607143 0.0198251 -0.00628426 0.0465487 0 0 0 0.00353501 0 0 0 0.0504677"
#parse = parse.split()
#parse = map(float, parse)
#coords[0]=parse[0]
#coords[1]=parse[1]
#coords[2]=parse[2]
#rk=parse[3]
#timeDes=parse[5]
#v2=parse[6]
#alpha=parse[7]
#tvisc=parse[8]
#tke=parse[10]
#tdr=parse[9]
#dudx=np.asarray(parse[11:20])
#dudx=dudx.reshape(3,3)
#dudx=np.transpose(dudx)
#avgDudx=np.asarray(parse[20:29])
#avgDudx=avgDudx.reshape(3,3)
#avgDudx=np.transpose(avgDudx)
#nuSF=np.asarray(parse[29:38])
#nuSF=nuSF.reshape(3,3)
#nuSF=np.transpose(nuSF)

In [84]:
pTauSGRS = np.zeros((9))
print pTauSGRS

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
tkeMin = .00000001
perotC = 1.0
BLKOL = 1.0

nuSF = np.array([[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]])

def getEig(mat):
    ident = np.zeros((3,3))
    for i in range(0,3):
      ident[i][i] = 1.0

    # force symmetry
    rtemp = np.zeros((3,3))
    for i in range(0,3):
      for j in range(0,3):
        rtemp[i][j] = mat[i][j] + mat[j][i]

    r2 = 0.5*rtemp

    p1 = r2[0][1]**2 + r2[0][2]**2 + r2[1][2]**2

    q = (r2[1][1]+r2[2][2]+r2[0][0])/3.0
    p2 = (r2[0][0] - q)**2 + (r2[1][1] - q)**2 + (r2[2][2] - q)**2 + 2.0 * p1
    p = np.sqrt(max(p2,1.0e-12)/6.0)
    B = (1.0/max(p,1.0e-12)) * (r2-q*ident)
    detB = B[0][0] * (B[1][1]*B[2][2] - B[2][1]*B[1][2]) - B[0][1] * (B[1][0]*B[2][2] - B[2][0]*B[1][2]) + B[0][2] * (B[1][0]*B[2][1] - B[2][0]*B[1][1])
    r = 0.5*detB

    # In exact arithmetic for a symmetric matrix  -1 <= r <= 1
    # but computation error can leave it slightly outside this range.
    if (r <= -1.0):
       phi = np.pi/3.0
    elif (r >= 1.0): 
       phi = 0.0
    else:
       phi = math.acos(r)/3.0

    # the eigenvalues satisfy eig3 <= eig2 <= eig1
    ev1 = q + 2.0 * p * np.cos(phi)
    ev3 = q + 2.0 * p * np.cos(phi + (2.0*np.pi/3.0))
    ev2 = 3.0 * q - ev1 - ev3
    
    eig = max(np.abs(ev1), np.abs(ev2))
    eig = max(eig, np.abs(ev3))
    
    print (ev1, ev2, ev3)
        
    return eig

    
#NOTE: dudx is defined with second index corresponding to velocity component
du = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    for m in range(0,3):
      du[i][j] = du[i][j] + (dudx[m][i]-avgDudx[m][i])*nuSF[j][m]

tau = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    tau[i][j] = du[i][j] + du[j][i]

r2 = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    for m in range(0,3):
      r2[i][j] = r2[i][j] + dudx[i][m]*tau[j][m]

P = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    P[i][j] = 0.5*(r2[i][j] + r2[j][i])

uu = P

du = np.zeros((3,3))
iden = np.zeros((3,3))
for i in range(0,3):
  iden[i][i] = 1.0

for i in range(0,3):
  for j in range(0,3):
    for m in range(0,3):
      du[i][j] = du[i][j] + avgDudx[m][i]*tvisc*iden[j][m]

tau = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    tau[i][j] = du[i][j] + du[j][i]

tau = alpha*tau

tau = tau - alpha*2.0/3.0*tke*iden

P = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    for m in range(0,3):
      P[i][j] = P[i][j] + dudx[i][m]*tau[j][m]

du = P
P = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    P[i][j] = du[i][j] + du[j][i]

P = 0.5*P

# add contribution from expected SGET (not really uu here)
P = P + uu

# now get L^-1_{im} * M_{mj}
rd = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    for m in range(0,3):
      rd[i][j] = rd[i][j] + P[j][m] * metric[m][i]

rd = rd * (max(1.5*alpha*v2,tkeMin))**(-1.5)

# magnitude based
rdTemp = 0.0
for i in range(0,3):
  for j in range(0,3):
    rdTemp = rdTemp + rd[i][j]*rd[i][j]

rdTemp = np.sqrt(rdTemp)

# least-resolved orientation max(lambda_rd)
maxEig = getEig(rd)

rd = maxEig
maxPM = rd

rd = max(min(rd,rdTemp),1.0e-6)

rd = min(rd,30.0/perotC) # arbitrary, figure out why we get blow-up spots
fd = perotC*max(rd,1.0e-8)

if(alpha >= 1.0):
    fd = min(fd,1.0)
if(alpha <= min(BLKOL*np.sqrt(visc*tdr)/tke,1.0)):
    fd = max(fd,1.0)
                 

print ("rk from calc ", fd)
print ("rk from code ", rk)
print ("coords ", coords)
print ("timeDES ", timeDes)
print ("v2 ", v2)
print ("alpha ", alpha)
print ("tvisc ", tvisc)
print ("tke ", tke)
print ("tdr ", tdr)
print ("dudx ", dudx)
print ("avgDudx ", avgDudx)
print ("nuSF ", nuSF)

0.0028563576413223038 7.146225148094154e-09 -0.0028387023090656735
rk from calc  1.0
rk from code  0.3635492506619635
coords  [ 0.89198819 -0.11835677 -0.0238724 ]
timeDES  3.58569035659e-07
v2  31.2867
alpha  1.0
tvisc  2.8226385e-09
tke  0.052252516556007766
tdr  145725.12224856217
dudx  [[ 5.81513586e+03  1.52582022e+04  1.57623460e-02]
 [-2.21632334e+03 -5.81523929e+03 -5.48039506e-03]
 [ 5.69005094e+00  1.49380177e+01 -1.18290272e-02]]
avgDudx  [[ 5.81513586e+03  1.52582022e+04  1.57623460e-02]
 [-2.21632334e+03 -5.81523929e+03 -5.48039506e-03]
 [ 5.69005094e+00  1.49380177e+01 -1.18290272e-02]]
nuSF  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
#0.11071952219925242 0.004020331109018421 -0.04110751104257543
#rk from calc  0.11071952219925242
#rk from code  0.112311
#coords  [1.1088  1.19195 2.74889]
#timeDES  1.16305
#v2  0.673139
#alpha  0.981859
#tvisc  0.172237
#tke  1.6456
#tdr  1.4149
#dudx  [[ 0.0467721  0.03631   -0.223903 ]
# [-0.208942   0.15586    0.0856052]
# [ 0.0439817  0.224608  -0.2139   ]]
#avgDudx  [[-3.40710e-04 -2.77373e-03 -6.07143e-03]
# [-1.21604e+00  5.47406e-03  1.98251e-02]
# [-7.88690e-03  2.23157e-03 -6.28426e-03]]
#nuSF  [[0.0465487  0.         0.        ]
# [0.         0.00353501 0.        ]
# [0.         0.         0.0504677 ]]


nDim = 3

#      // Eigenvalue decomposition of metric tensor
#      EigenDecomposition::sym_diagonalize<double>(Mij, Q, D);
#
#      // initialize M43 to 0
#      double M43[3][3];
#      for (unsigned i = 0; i < nDim_; ++i)
#        for (unsigned j = 0; j < nDim_; ++j)
#          M43[i][j] = 0.0;
#
#      const double fourThirds = 4.0/3.0;
#
#      for (unsigned l = 0; l < nDim_; l++) {
#        const double D43 = stk::math::pow(D[l][l], fourThirds);
#        for (unsigned i = 0; i < nDim_; i++) {
#          for (unsigned j = 0; j < nDim_; j++) {
#            M43[i][j] += Q[i][l] * Q[j][l] * D43;
#          }
#        }
#      }
#
#     // zeroing out tesnors
#      for (unsigned i = 0; i < nDim_; ++i) {
#        for (unsigned j = 0; j < nDim_; ++j) {
#          p_tauSGRS[i*nDim_ + j] = 0.0;
#          p_tauSGET[i*nDim_ + j] = 0.0;
#          p_tau[i*nDim_ + j] = 0.0;
#          p_Psgs[i*nDim_ + j] = 0.0;
#        }
#      }
#
#      const double CM43 = tams_utils::get_M43_constant<double, 3>(D, CMdeg_);
#
#      const double epsilon13 = stk::math::pow(tdr[k], 1.0/3.0);

alpha = 1.0
tvisc = 0.0000000028226385
tke = 0.052252516556007766
avgDudx = np.array([[5815.135862199717848853,15258.202229787613759981,0.015762345965326219],[-2216.32333984757633516,-5815.239285149380521034,-0.005480395056548737],[5.690050943440175146,14.938017730791141702,-0.01182902716973124]])
dudx = avgDudx
metric = np.array([[0.005243657027190821,-0.001994924796099943,0.0],[-0.001994924796099943,0.000772004663223833,0.0],[0.0,0.0,0.005569860945288242]])
timeDes = 0.000000323354832376

pTauSGRS = np.zeros((9))
pTauSGET = np.zeros((9))
pTau = np.zeros((9))
pPsgs = np.zeros((9))
for i in range(0,3):
  for j in range(0,3):
    coeffSGRS = alpha * tvisc
    pTauSGRS[i*nDim + j] = avgDudx[j][i] + avgDudx[i][j]
    pTauSGRS[i*nDim + j] *= coeffSGRS

    #for l in range(0,3):
    #  #coeffSGET = 1.0 * CM43 * tdr**(1.0/3.0);
    #  fluctDudxJl = dudx[l][j] - avgDudx[l][j]
    #  fluctDudxIl = dudx[l][i] - avgDudx[l][i]
    #  #pTauSGET[i*nDim + j] += coeffSGET * (M43[i][l] * fluctDudxJl +
    #  #                                           M43[j][l] * fluctDudxIl)
    #  pTauSGET[i*nDim + j] += (nuSF[i][l] * fluctDudxJl + nuSF[j][l] * fluctDudxIl)
    
# Calculate the full subgrid stress including the isotropic portion
for i in range(0,3):
  for j in range(0,3):
    pTau[i*nDim + j] = pTauSGRS[i*nDim + j] #+ pTauSGET[i*nDim + j]
  pTau[i*nDim + i] -= 2.0/3.0*alpha*tke

# Calculate the SGS production PSGS_ij = 1/2(tau_ik*djuk + tau_jk*diuk)
# where diuj is the instantaneous velocity gradients
for i in range(0,3):
  for j in range(0,3):
    for l in range(0,3):
      pPsgs[i*nDim + j] += pTau[i*nDim + l] * dudx[j][l] + pTau[j*nDim + l] * dudx[i][l]
    pPsgs[i*nDim+ j] *= 0.5


PM = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    for l in range(0,3):
      PM[i][j] += pPsgs[i*nDim + l] * metric[l][j]

# Scale PM first
TimeKE = timeDes
v2 = 1.0/0.22 * (tvisc / TimeKE)
print (v2)
PMscale = (1.5*alpha*v2)**(-1.5)
print(PMscale)

for i in range(0,3):
  for j in range(0,3):
    PM[i][j] = PM[i][j] * PMscale

maxEig = np.linalg.eig(PM)[0].max()

# magnitude based
rdTemp = 0.0
for i in range(0,3):
  for j in range(0,3):
    rdTemp = rdTemp + PM[i][j]*PM[i][j]

rdTemp = np.sqrt(rdTemp)
print(rdTemp)
print(maxEig)

# Update the instantaneous resAdeq field
resAdeq = maxEig
# FIXME: Limiters as in CDP...
resAdeq = min(resAdeq,30.0)

if (alpha >= 1.0):
  resAdeq = min(resAdeq,1.0)

print (resAdeq)

0.03967831532228643
68.87050615329625
125.85939812400026
5.6812010273639615
1.0


In [19]:
dudx = "-0.406557E+00  0.275124E+00  0.312125E+00  0.344887E+01 -0.229688E+00 -0.118359E+01  0.184561E+00  0.231011E+00  0.658679E+00"
dudx = dudx.split()
dudx = map(float, dudx)
dudx = np.asarray(dudx)

In [36]:
parse = "0.554399E+00  0.729389E+00  0.294524E+01  0.118770E+01  0.118770E+01  0.894835E+00  0.469376E+00  0.884520E+00  0.924030E-01  0.128250E+01  0.114762E+01 -0.685608E+00  0.218757E+00  0.484385E+00  0.507100E+01 -0.428382E-01 -0.189557E+01 -0.350813E+00  0.218780E+00  0.752538E+00 -0.118100E-01 -0.852823E-02  0.615356E-02  0.331922E+01  0.817536E-01  0.462339E+00 -0.393735E-01 -0.478547E-01 -0.107060E+00  0.452622E-01 -0.820524E-11  0.608203E-12 -0.820524E-11  0.327041E-02 -0.595815E-09  0.608203E-12 -0.595815E-09  0.490728E-01"
parse = parse.split()
parse = map(float, parse)

In [39]:
parse[0:4]

[0.554399, 0.729389, 2.94524, 1.1877]

In [34]:
avgDudx = np.array([[-14943.787867,1131.806894,1.591208],[-103649.325526,21503.644783,16.172263],[-108024.047705,22005.83053,5.55532]])
alpha = 1.0
tvisc = 0.000038
density = 1.225
tke = 64.744392
avgVel = np.array([ -0.448885,-1.718769,-1.117268])
vel = np.array([-0.474909,-1.750422,-1.04799])

tij = np.zeros((3,3))
for i in range(0,3):
    for j in range(0,3):
        avgSij = 0.5 * (avgDudx[i][j] + avgDudx[j][i])
        tij[i][j] = 2.0 * alpha * (2.0-alpha) * tvisc * avgSij
    
    tij[i][i] -= 2.0/3.0 * alpha * density * tke


Pij = np.zeros((3,3))
for i in range(0,3):
    for j in range(0,3):
        Pij[i][j] = 0.0
        for m in range(0,3):
            Pij[i][j] += avgDudx[i][m] * tij[j][m] + avgDudx[j][m] * tij[i][m]
        Pij[i][j] *= 0.5


P_res = 0.0
for i in range(0,3):
    for j in range(0,3):
        P_res += density * avgDudx[i][j] * ((avgVel[i] - vel[i]) * (avgVel[j] - vel[j]))

instProd = 0.0
for i in range(0,3):
    instProd += Pij[i][i]

instProd -= P_res

#prodWeightAvg = np.max(1.0 - dt / prodAvgTime, 0.0)
#prodWeightInst = np.min(dt / prodAvgTime, 1.0)

print (instProd)

566100.6684004165
